export const quotes = [
    { id: 1, text: "Głupiec myśli, że jest mądry, ale mądry człowiek wie, że jest głupcem.", author: "William Shakespeare, Jak wam się podoba" },
    { id: 2, text: "Lepiej milczeć ryzykując, że uznają cię za głupca, niż odezwać się i rozwiać wszelkie wątpliwości.", author: "Maurice Switzer, Mrs. Goose, Her Book" },
    { id: 3, text: "Kiedy znajdziesz się po stronie większości, czas na reformę (lub zatrzymanie się i refleksję).", author: "Mark Twain" },
    { id: 4, text: "Kiedy ktoś cię kocha, sposób, w jaki o tobie mówi, jest inny. Czujesz się bezpiecznie i komfortowo.", author: "Jess C. Scott, The Intern" },
    { id: 5, text: "Poznanie samego siebie jest początkiem wszelkiej mądrości.", author: "Arystoteles" },
    { id: 6, text: "Jedyną prawdziwą mądrością jest wiedza o tym, że nic nie wiesz.", author: "Sokrates" },
    { id: 7, text: "Najsmutniejszym aspektem dzisiejszego życia jest to, że nauka gromadzi wiedzę szybciej, niż społeczeństwo gromadzi mądrość.", author: "Isaac Asimov" },
    { id: 8, text: "Trzymaj się mocno marzeń, bo jeśli marzenia umierają, życie staje się ptakiem ze złamanym skrzydłem, który nie potrafi latać.", author: "Langston Hughes" },
    { id: 9, text: "Licz swoje lata przez przyjaciół, nie lata. Licz swoje życie przez uśmiechy, nie łzy.", author: "John Lennon" },
    { id: 10, text: "W dobrym pokoju pełnym książek czujesz w tajemniczy sposób, że przyswajasz mądrość zawartą we wszystkich książkach przez swoją skórę, nawet ich nie otwierając.", author: "Mark Twain" },
    { id: 11, text: "Obyś żył każdego dnia swojego życia.", author: "Jonathan Swift" },
    { id: 12, text: "Każdy głupiec może wiedzieć. Chodzi o to, by zrozumieć.", author: "Albert Einstein" },
    { id: 13, text: "Oznaką wykształconego umysłu jest umiejętność przyjęcia myśli bez jej akceptacji.", author: "Arystoteles, Metafizyka" },
    { id: 14, text: "Sekret życia polega na tym, by upaść siedem razy i wstać osiem.", author: "Paulo Coelho, Alchemik" },
    { id: 15, text: "Nigdy nie śmiej się z żywych smoków.", author: "J.R.R. Tolkien" },
    { id: 16, text: "Jeśli to czytasz... Gratulacje, żyjesz. Jeśli to nie powód do uśmiechu, to nie wiem, co nim jest.", author: "Chad Sugg, Monsters Under Your Head" },
    { id: 17, text: "Nie ma na świecie ani szczęścia, ani nieszczęścia; istnieje tylko porównanie jednego stanu z drugim, nic więcej. Ten, kto doświadczył najgłębszego smutku, najlepiej potrafi odczuwać najwyższe szczęście. Musieliśmy doświadczyć, czym jest śmierć, Morrel, aby docenić radości życia. Żyj więc i bądź szczęśliwy, ukochane dziecię mojego serca, i nigdy nie zapominaj, że aż do dnia, gdy Bóg zdecyduje się objawić człowiekowi przyszłość, cała ludzka mądrość zawiera się w tych dwóch słowach: 'Czekaj i miej nadzieję.'", author: "Alexandre Dumas" },
    { id: 18, text: "Pomyśl, zanim coś powiesz. Czytaj, zanim zaczniesz myśleć.", author: "Fran Lebowitz, The Fran Lebowitz Reader" },
    { id: 19, text: "Nigdy nie pozwól, by poczucie moralności powstrzymało cię przed zrobieniem tego, co właściwe.", author: "Isaac Asimov, Fundacja" },
    { id: 20, text: "Najlepszym wskaźnikiem charakteru człowieka jest to, jak traktuje ludzi, którzy nie mogą mu pomóc, oraz jak traktuje tych, którzy nie mogą się bronić.", author: "Abigail Van Buren" },
    { id: 21, text: "Życie nieprzeanalizowane nie jest warte przeżycia.", author: "Sokrates" },
    { id: 22, text: "Zamień swoje rany na mądrość.", author: "Oprah Winfrey" },
    { id: 23, text: "Najprostsze rzeczy są też najbardziej niezwykłe, a tylko mędrcy potrafią je dostrzec.", author: "Paulo Coelho, Alchemik" },
    { id: 24, text: "Są trzy rzeczy, których boją się wszyscy mędrcy: morza podczas burzy, nocy bez księżyca i gniewu łagodnego człowieka.", author: "Patrick Rothfuss, Strach mędrca" },
    { id: 25, text: "To niebezpieczna rzecz, Frodo, wychodzić za drzwi. Stajesz na drodze, a jeśli nie trzymasz się mocno, nie wiadomo, dokąd możesz zostać zaniesiony.", author: "J.R.R. Tolkien, Władca Pierścieni" },
    { id: 26, text: "Rozgniewani ludzie nie zawsze są mądrzy.", author: "Jane Austen, Duma i uprzedzenie" },
    { id: 27, text: "Wczoraj byłem sprytny, więc chciałem zmienić świat. Dziś jestem mądry, więc zmieniam siebie.", author: "Rumi" },
    { id: 28, text: "Przez trzy sposoby możemy się uczyć mądrości: po pierwsze przez refleksję, co jest najwznioślejsze; po drugie przez naśladowanie, co jest najłatwiejsze; po trzecie przez doświadczenie, co jest najgorzkiejsze.", author: "Konfucjusz" },
    { id: 29, text: "Nie piszesz swojego życia słowami... Piszesz je czynami. To, co myślisz, nie ma znaczenia. Liczy się tylko to, co robisz.", author: "Patrick Ness, Siedem minut po północy" },
    { id: 30, text: "Zdumiewające, jak całkowita jest iluzja, że piękno to dobro.", author: "Lew Tołstoj, Sonata Kreutzerowska" },
    { id: 31, text: "Nie porównuj się z innymi. Porównuj się z tym, kim byłeś wczoraj.", author: "Bill Gates" },
    { id: 32, text: "Nie bój się popełniać błędów. To one prowadzą do sukcesu.", author: "Albert Einstein" },
    { id: 33, text: "Nauka to podróż, a nie cel.", author: "Anonim" },
    { id: 34, text: "Małe kroki są kluczem do wielkich osiągnięć.", author: "Laozi" },
    { id: 35, text: "Nie musisz być wielki, żeby zacząć, ale musisz zacząć, żeby być wielki. ", author: "Zig Ziglar" },
  ];
  